// <auto-generated />
using System;
using Hope_tracKeR_back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hope_tracKeR_back.Migrations
{
    [DbContext(typeof(HTContext))]
    [Migration("20260612183120_changeUserData")]
    partial class changeUserData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Branch = "ул. Пушкина 1",
                            Building = "Корпус 1",
                            Floor = 1,
                            Room = "Кабинет 101"
                        },
                        new
                        {
                            Id = 2,
                            Branch = "ул. Пушкина 1",
                            Building = "Корпус 1",
                            Floor = 1,
                            Room = "Кабинет 102"
                        },
                        new
                        {
                            Id = 3,
                            Branch = "ул. Толстого 31",
                            Building = "Корпус 4",
                            Floor = 3,
                            Room = "Кабинет 314"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Logitech"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SerialId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BrandId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 1,
                            BrandId = 1,
                            Category = 0,
                            Name = "Монитор Samsung Odyssey",
                            SerialId = "SAMS-OD-001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AddedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 2,
                            BrandId = 3,
                            Category = 0,
                            Name = "Ноутбук LG Gram",
                            SerialId = "LG-GRAM-002",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AddedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 1,
                            BrandId = 4,
                            Category = 0,
                            Name = "Клавиатура Logitech MX",
                            SerialId = "LOG-MX-003",
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AddedDate = new DateTime(2024, 3, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 3,
                            BrandId = 2,
                            Category = 1,
                            Name = "Бумага A4 500л",
                            SerialId = "PAP-A4-004",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AddedDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 2,
                            BrandId = 1,
                            Category = 1,
                            Name = "Картридж для принтера",
                            SerialId = "CRTG-005",
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AddedDate = new DateTime(2024, 1, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            AddressId = 1,
                            BrandId = 2,
                            Category = 1,
                            Name = "USB Flash Drive 32GB",
                            SerialId = "USB-32-006",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.ItemAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemAttributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Name = "Диагональ",
                            Value = "27 дюмов"
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 1,
                            Name = "Разрешение",
                            Value = "2560x1440"
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 1,
                            Name = "Герцовка",
                            Value = "165Hz"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ItemId");

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Description = "Монитор не включается, индикатор питания не горит",
                            Diagnosis = "Неисправен блок питания, замена конденсаторов",
                            EndDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Description = "Ноутбук зависает при загрузке Windows",
                            Diagnosis = "Ожидается диагностика",
                            ItemId = 2,
                            StartDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            Description = "Клавиатура не печатает буквы, некоторые кнопки залипли",
                            Diagnosis = "Механическое повреждение, требуется чистка",
                            ItemId = 3,
                            StartDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            Description = "Флешка не определяется компьютером",
                            Diagnosis = "Сбой контроллера, данные восстановлены",
                            EndDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            StartDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            Description = "Монитор моргает и периодически гаснет",
                            Diagnosis = "Неисправен шлейф матрицы",
                            ItemId = 1,
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 2,
                            Description = "Ноутбук сильно греется и выключается",
                            Diagnosis = "Ожидается диагностика",
                            ItemId = 2,
                            StartDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Role")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Рустам Вордович",
                            Login = "word365",
                            Password = "21232F297A57A5A743894A0E4A801FC3",
                            Role = 0
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Родион Экселович",
                            Login = "excel2003",
                            Password = "21232F297A57A5A743894A0E4A801FC3",
                            Role = 0
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Моисей Шарпович",
                            Login = "sharp3000",
                            Password = "21232F297A57A5A743894A0E4A801FC3",
                            Role = 0
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Михаил Реактович",
                            Login = "react2026",
                            Password = "21232F297A57A5A743894A0E4A801FC3",
                            Role = 0
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Кирилл TracKeR",
                            Login = "legenda212",
                            Password = "8C728E685DDDE9F7FBBC452155E29639",
                            Role = 1
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.ItemAttribute", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Item", "Item")
                        .WithMany("Attributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Repair", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
