// <auto-generated />
using System;
using Hope_tracKeR_back.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hope_tracKeR_back.Migrations
{
    [DbContext(typeof(HTContext))]
    [Migration("20260620084941_EditColumnAuditLog")]
    partial class EditColumnAuditLog
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Branch")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Building")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Floor")
                        .HasColumnType("integer");

                    b.Property<string>("Room")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Addresses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Branch = "ул. Пушкина 1",
                            Building = "Корпус 1",
                            Floor = 1,
                            Room = "Кабинет 101"
                        },
                        new
                        {
                            Id = 2,
                            Branch = "ул. Пушкина 1",
                            Building = "Корпус 1",
                            Floor = 1,
                            Room = "Кабинет 102"
                        },
                        new
                        {
                            Id = 3,
                            Branch = "ул. Толстого 31",
                            Building = "Корпус 4",
                            Floor = 3,
                            Room = "Кабинет 314"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.AuditLog", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EntityId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EntityName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserLogin")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Brand", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Samsung"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Dexp"
                        },
                        new
                        {
                            Id = 3,
                            Name = "LG"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Logitech"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Svetocopy"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Kite"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Attache"
                        },
                        new
                        {
                            Id = 8,
                            Name = "OfficeSpace"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Монитор"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Ноутбук"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Картридж"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Моноблок"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Staff")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Петров А.А.",
                            Staff = "Врач"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Сидоров С.С.",
                            Staff = "Заведующий хоз. товарами"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Иванов Д.Д.",
                            Staff = "Мастер над монетой"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Issuance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Issuances");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<int>("BrandId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("character varying(13)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("BrandId");

                    b.ToTable("Items");

                    b.HasDiscriminator().HasValue("Item");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.ItemAttribute", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.ToTable("ItemAttributes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ItemId = 1,
                            Name = "Диагональ",
                            Value = "27 дюмов"
                        },
                        new
                        {
                            Id = 2,
                            ItemId = 1,
                            Name = "Разрешение",
                            Value = "2560x1440"
                        },
                        new
                        {
                            Id = 3,
                            ItemId = 1,
                            Name = "Герцовка",
                            Value = "165Hz"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Refill", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Refills");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            EndDate = new DateTime(2025, 6, 2, 14, 30, 0, 0, DateTimeKind.Utc),
                            ItemId = 101,
                            StartDate = new DateTime(2025, 6, 1, 10, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 1,
                            ItemId = 103,
                            StartDate = new DateTime(2025, 6, 5, 9, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            ItemId = 102,
                            StartDate = new DateTime(2025, 6, 10, 11, 15, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            EndDate = new DateTime(2025, 6, 13, 16, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 104,
                            StartDate = new DateTime(2025, 6, 12, 8, 30, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            ItemId = 105,
                            StartDate = new DateTime(2025, 6, 15, 14, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 5
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Repair", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("text");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("Repairs");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            Description = "Монитор не включается, индикатор питания не горит",
                            Diagnosis = "Неисправен блок питания, замена конденсаторов",
                            EndDate = new DateTime(2025, 5, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 1,
                            StartDate = new DateTime(2025, 5, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            Description = "Ноутбук зависает при загрузке Windows",
                            Diagnosis = "Ожидается диагностика",
                            ItemId = 2,
                            StartDate = new DateTime(2025, 5, 20, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            Description = "Клавиатура не печатает буквы, некоторые кнопки залипли",
                            Diagnosis = "Механическое повреждение, требуется чистка",
                            ItemId = 3,
                            StartDate = new DateTime(2025, 5, 25, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 4,
                            AddressId = 1,
                            Description = "Флешка не определяется компьютером",
                            Diagnosis = "Сбой контроллера, данные восстановлены",
                            EndDate = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            ItemId = 6,
                            StartDate = new DateTime(2025, 5, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 1,
                            UserId = 1
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 1,
                            Description = "Монитор моргает и периодически гаснет",
                            Diagnosis = "Неисправен шлейф матрицы",
                            ItemId = 1,
                            StartDate = new DateTime(2025, 6, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = 1
                        },
                        new
                        {
                            Id = 6,
                            AddressId = 2,
                            Description = "Ноутбук сильно греется и выключается",
                            Diagnosis = "Ожидается диагностика",
                            ItemId = 2,
                            StartDate = new DateTime(2025, 6, 3, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = 0,
                            UserId = 1
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FullName = "Рустам Вордович",
                            Login = "word365",
                            Password = "21232F297A57A5A743894A0E4A801FC3"
                        },
                        new
                        {
                            Id = 2,
                            FullName = "Родион Экселович",
                            Login = "excel2003",
                            Password = "21232F297A57A5A743894A0E4A801FC3"
                        },
                        new
                        {
                            Id = 3,
                            FullName = "Моисей Шарпович",
                            Login = "sharp3000",
                            Password = "21232F297A57A5A743894A0E4A801FC3"
                        },
                        new
                        {
                            Id = 4,
                            FullName = "Михаил Реактович",
                            Login = "react2026",
                            Password = "21232F297A57A5A743894A0E4A801FC3"
                        },
                        new
                        {
                            Id = 5,
                            FullName = "Кирилл TracKeR",
                            Login = "legenda212",
                            Password = "8C728E685DDDE9F7FBBC452155E29639"
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.WriteOff", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ItemId")
                        .HasColumnType("integer");

                    b.Property<int>("UserId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ItemId");

                    b.HasIndex("UserId");

                    b.ToTable("WriteOffs");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Cartridge", b =>
                {
                    b.HasBaseType("Hope_tracKeR_back.Models.Entities.Item");

                    b.Property<string>("PrinterModel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.ToTable("Items", t =>
                        {
                            t.Property("Status")
                                .HasColumnName("Cartridge_Status");
                        });

                    b.HasDiscriminator().HasValue("Cartridge");

                    b.HasData(
                        new
                        {
                            Id = 100,
                            AddressId = 1,
                            BrandId = 1,
                            Name = "Тонер-картридж Samsung ML-1660",
                            PrinterModel = "ML-1660",
                            Status = 0
                        },
                        new
                        {
                            Id = 101,
                            AddressId = 1,
                            BrandId = 1,
                            Name = "Тонер-картридж Samsung SCX-4521F",
                            PrinterModel = "SCX-4521F",
                            Status = 2
                        },
                        new
                        {
                            Id = 102,
                            AddressId = 1,
                            BrandId = 3,
                            Name = "Картридж LG Printronix",
                            PrinterModel = "Printronix",
                            Status = 3
                        },
                        new
                        {
                            Id = 103,
                            AddressId = 2,
                            BrandId = 2,
                            Name = "Тонер Dexp DPP-250",
                            PrinterModel = "DPP-250",
                            Status = 1
                        },
                        new
                        {
                            Id = 104,
                            AddressId = 2,
                            BrandId = 1,
                            Name = "Картридж Samsung CLP-315",
                            PrinterModel = "CLP-315",
                            Status = 1
                        },
                        new
                        {
                            Id = 105,
                            AddressId = 3,
                            BrandId = 3,
                            Name = "Картридж LG LBP-1210",
                            PrinterModel = "LBP-1210",
                            Status = 1
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Consumable", b =>
                {
                    b.HasBaseType("Hope_tracKeR_back.Models.Entities.Item");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("Consumable");

                    b.HasData(
                        new
                        {
                            Id = 6,
                            AddressId = 1,
                            BrandId = 5,
                            Name = "Бумага А4 Svetocopy",
                            Quantity = 50
                        },
                        new
                        {
                            Id = 7,
                            AddressId = 1,
                            BrandId = 5,
                            Name = "Бумага А3 Svetocopy",
                            Quantity = 20
                        },
                        new
                        {
                            Id = 8,
                            AddressId = 2,
                            BrandId = 6,
                            Name = "Скрепки 25 мм",
                            Quantity = 100
                        },
                        new
                        {
                            Id = 9,
                            AddressId = 3,
                            BrandId = 7,
                            Name = "Папка-регистратор Attache",
                            Quantity = 30
                        },
                        new
                        {
                            Id = 10,
                            AddressId = 2,
                            BrandId = 8,
                            Name = "Ручка шариковая OfficeSpace",
                            Quantity = 200
                        },
                        new
                        {
                            Id = 11,
                            AddressId = 1,
                            BrandId = 7,
                            Name = "Стикеры самоклеящиеся",
                            Quantity = 15
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Device", b =>
                {
                    b.HasBaseType("Hope_tracKeR_back.Models.Entities.Item");

                    b.Property<DateTime>("AddedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("integer");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.HasIndex("CategoryId");

                    b.HasIndex("EmployeeId");

                    b.HasDiscriminator().HasValue("Device");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressId = 1,
                            BrandId = 1,
                            Name = "Монитор Samsung Odyssey",
                            AddedDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Utc),
                            CategoryId = 1,
                            SerialNumber = "SAMS-OD-001",
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            AddressId = 2,
                            BrandId = 3,
                            Name = "Ноутбук LG Gram",
                            AddedDate = new DateTime(2024, 2, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CategoryId = 2,
                            EmployeeId = 1,
                            SerialNumber = "LG-GRAM-002",
                            Status = 2
                        },
                        new
                        {
                            Id = 3,
                            AddressId = 1,
                            BrandId = 4,
                            Name = "Моноблок Logitech MX",
                            AddedDate = new DateTime(2024, 3, 5, 0, 0, 0, 0, DateTimeKind.Utc),
                            CategoryId = 4,
                            SerialNumber = "LOG-MX-003",
                            Status = 0
                        },
                        new
                        {
                            Id = 5,
                            AddressId = 2,
                            BrandId = 1,
                            Name = "Картридж для принтера",
                            AddedDate = new DateTime(2024, 4, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            CategoryId = 3,
                            SerialNumber = "CRTG-005",
                            Status = 0
                        });
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Issuance", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Device", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Brand", "Brand")
                        .WithMany()
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.ItemAttribute", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Item", "Item")
                        .WithMany("Attributes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Refill", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Cartridge", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Repair", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Device", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.WriteOff", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Device", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Device", b =>
                {
                    b.HasOne("Hope_tracKeR_back.Models.Entities.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hope_tracKeR_back.Models.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId");

                    b.Navigation("Category");

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Hope_tracKeR_back.Models.Entities.Item", b =>
                {
                    b.Navigation("Attributes");
                });
#pragma warning restore 612, 618
        }
    }
}
